safety_bubble_node:
  ros__parameters:
    bubble_radius: 0.83
    speed_min: 0.8
    speed_max: 2.0
    window_size: 9
    perception_fov_deg: 58.0
    kp: 1.5
    ki: 0.0
    kd: 0.004
    steering_fov_deg: 45.0

    smooth_steer: false
    max_offset: 5
    safety_distance: 1.0
